<?php

return [
    'app' => [
        'name' => 'xpsystems',
        'version' => '5.4.0',
        'copyright_year' => (int) date('Y'),
        'primary_domains' => ['xpsystems.eu', 'xpsystems.de', 'xpsys.de', 'xpsys.eu'],
        'status_url' => 'https://status.xpsystems.eu',
        'status_api_url' => 'https://status.xpsystems.eu/api/status',
        'github_org_url' => 'https://github.com/xpsystems',
        'github_token' => getenv('GITHUB_TOKEN') ?: '',
    ],

    'brand' => [
        'name'              => 'xpsystems',
        'version'           => '5.4.0',
        'tagline'           => 'German Web-Provider',
        'sub_entity_of'     => 'ternis.dev (ternis-edv)',
        'parent_url'        => 'https://ternis-edv.de',
        'parent_domain'     => 'ternis.dev',
        'open_source_hub'   => 'https://oss.ternis.org',
        'nameservers'       => ['one.ns.ternis.net', 'two.ns.ternis.net'],
        'transition_notice' => 'xpsystems (xpsystems.eu & xpsystems.de) has transitioned into ternis.dev (ternis-edv). Infrastructure, Anycast DNS and open-source operations continue under the ternis ecosystem.',
        'description'       => 'European infrastructure, digital sovereignty, and developer-first tooling — operated as a sub-entity of ternis-edv (ternis.dev) from Germany.',
        'domains'           => ['xpsystems.eu', 'xpsystems.de', 'xpsys.de'],
    ],

    'nameservers' => [
        'primary'   => 'one.ns.ternis.net',
        'secondary' => 'two.ns.ternis.net',
        'domain'    => 'ternis.net',
    ],

    'parent_entity' => [
        'name'        => 'ternis-edv',
        'brand'       => 'ternis.dev',
        'legal_name'  => 'ternis-edv',
        'url'         => 'https://ternis-edv.de',
        'domain'      => 'ternis-edv.de',
        'alt_url'     => 'https://ternis.dev',
        'alt_domain'  => 'ternis.dev',
        'oss_url'     => 'https://oss.ternis.org',
        'description' => 'Parent IT organisation & enterprise systems',
    ],

    'subdomains' => [
        'main'       => ['www', 'xpsystems'],
        'status'     => ['status'],
        'contact'    => ['contact'],
        'domains'    => ['domains'],
        'opensource' => ['opensource', 'oss'],
    ],

    // Navigation links per subdomain or global
    'nav' => [
        ['label' => 'Services',   'href' => '#services',                    'external' => false, 'contexts' => ['main']],
        ['label' => 'Team',       'href' => '#team',                        'external' => false, 'contexts' => ['main']],
        ['label' => 'Status',     'href' => 'https://status.xpsystems.eu',   'external' => true,  'route' => '/status'],
        ['label' => 'Domains',    'href' => 'https://domains.xpsystems.eu',  'external' => true,  'route' => '/domains'],
        ['label' => 'OpenSource', 'href' => 'https://opensource.xpsystems.eu', 'external' => true,  'route' => '/opensource'],
        ['label' => 'Contact',    'href' => 'https://contact.xpsystems.eu',  'external' => true,  'route' => '/contact'],
        ['label' => 'GitHub',     'href' => 'https://github.com/xpsystems',  'external' => true],
    ],

    'footer_links' => [
        ['label' => 'GitHub',        'href' => 'https://github.com/xpsystems'],
        ['label' => 'Status',        'href' => 'https://status.xpsystems.eu'],
        ['label' => 'ternis.dev',    'href' => 'https://ternis.dev'],
        ['label' => 'oss.ternis.org', 'href' => 'https://oss.ternis.org'],
        ['label' => 'ternis-edv.de', 'href' => 'https://ternis-edv.de'],
        ['label' => 'EuropeHost',    'href' => 'https://europehost.eu'],
        ['label' => 'eu-data.org',   'href' => 'https://eu-data.org'],
        ['label' => 'MTEX.dev',      'href' => 'https://mtex.dev'],
        ['label' => 'Impressum',     'href' => '/impressum'],
        ['label' => 'Privacy',       'href' => '/privacy'],
    ],

    'hero_ctas' => [
        [
            'label'   => 'GitHub',
            'href'    => 'https://github.com/xpsystems',
            'primary' => false,
        ],
        [
            'label'   => 'System Status',
            'href'    => 'https://status.xpsystems.eu',
            'primary' => true,
        ],
    ],

    'services' => [
        [
            'name'    => 'ternis.dev (ternis-edv)',
            'type'    => 'parent',
            'url'     => 'https://ternis-edv.de',
            'tagline' => 'Parent entity & enterprise IT systems — managing xpsystems infrastructure',
            'links'   => [
                ['label' => 'ternis.dev',     'href' => 'https://ternis.dev'],
                ['label' => 'ternis-edv.de', 'href' => 'https://ternis-edv.de'],
            ],
        ],
        [
            'name'    => 'EuropeHost.eu',
            'type'    => 'service',
            'url'     => 'https://europehost.eu',
            'tagline' => 'European hosting infrastructure',
            'links'   => [
                ['label' => 'eudomains.eu',  'href' => 'https://eudomains.eu'],
                ['label' => 'eushare.eu',    'href' => 'https://eushare.eu'],
                ['label' => 'dsc.pics',      'href' => 'https://dsc.pics'],
                ['label' => 'swiftshare.eu', 'href' => 'https://swiftshare.eu'],
            ],
        ],
        [
            'name'    => 'eu-data.org',
            'type'    => 'service',
            'url'     => 'https://eu-data.org',
            'tagline' => 'European Digital Sovereignty — GDPR-compliant alternatives',
            'links'   => [
                ['label' => 'mail-free.eu',  'href' => 'https://mail-free.eu'],
                ['label' => 'eu-search.org', 'href' => 'https://eu-search.org'],
            ],
        ],
        [
            'name'    => 'MTEX.dev',
            'type'    => 'partner',
            'url'     => 'https://mtex.dev',
            'tagline' => 'Building the tools we actually want to use',
            'links'   => [
                ['label' => 'getmy.name',      'href' => 'https://getmy.name'],
                ['label' => 'status.mtex.dev', 'href' => 'https://status.mtex.dev'],
            ],
        ],
        [
            'name'    => 'api-sandbox.de',
            'type'    => 'service',
            'url'     => 'https://api-sandbox.de',
            'tagline' => 'API development sandbox',
            'links'   => [],
        ],
        [
            'name'    => 'DNBX.de',
            'type'    => 'service',
            'url'     => 'https://dnbx.de',
            'tagline' => 'Authoritative Domain & Nameserver Intelligence API',
            'links'   => [
                ['label' => 'api/stats',       'href' => 'https://dnbx.de/api/stats'],
                ['label' => 'api/nameservers', 'href' => 'https://dnbx.de/api/nameservers'],
                ['label' => 'api/domains',     'href' => 'https://dnbx.de/api/domains'],
            ],
        ],
        [
            'name'    => 'xpsys.eu',
            'type'    => 'service',
            'url'     => 'https://xpsys.eu',
            'tagline' => 'Gateway for services & templates',
            'links'   => [],
        ],
    ],

    'team' => [
        [
            'name'        => 'Fabian Ternis',
            'role'        => 'Founder & Lead / ternis-edv',
            'url'         => 'https://fabianternis.de',
            'github'      => 'fabianternis',
            'email'       => 'f.ternis@xpsystems.eu',
            'img_url'     => 'https://github.com/fabianternis.png',
        ],
        [
            'name'        => 'Ramsay Brewer',
            'role'        => 'Developer',
            'url'         => 'https://dogwaterdev.de',
            'github'      => 'dogwaterdev',
            'email'       => 'ramsay@xpsystems.eu',
            'img_url'     => 'https://github.com/dogwaterdev.png',
        ],
    ],

    'contact' => [
        'title' => 'Get in Touch',
        'description' => "Official communication channels for xpsystems & the ternis ecosystem.",
        'primary_email' => 'xpsystems@ternismail.de',
        'emails' => [
            ['label' => 'Direct Inbox',      'email' => 'xpsystems@ternismail.de'],
            ['label' => 'General Inquiries', 'email' => 'contact@xpsystems.eu'],
            ['label' => 'Germany Support',   'email' => 'contact@xpsystems.de'],
        ],
        'founder' => [
            'name'      => 'Fabian Ternis',
            'role'      => 'Founder / ternis-edv',
            'email'     => 'f.ternis@xpsystems.eu',
            'portfolio' => 'https://fabianternis.de',
            'github'    => 'https://github.com/fabianternis',
        ],
        'socials' => [
            ['platform' => 'Portfolio', 'handle' => 'fabianternis.de', 'url' => 'https://fabianternis.de', 'personal' => true],
            ['platform' => 'GitHub',    'handle' => '@fabianternis',    'url' => 'https://github.com/fabianternis', 'personal' => true],
            ['platform' => 'GitHub',    'handle' => '@xpsystems',       'url' => 'https://github.com/xpsystems'],
            ['platform' => 'Instagram', 'handle' => '@ternisfabian',    'url' => 'https://instagram.com/ternisfabian', 'personal' => true],
            ['platform' => 'Instagram', 'handle' => '@xpsystems.eu',    'url' => 'https://instagram.com/xpsystems.eu'],
            ['platform' => 'Instagram', 'handle' => '@xpsystems.de',    'url' => 'https://instagram.com/xpsystems.de'],
        ],
    ],

    'stats' => [
        [
            'value'      => '100+',
            'label'      => 'Domains Managed',
            'url'        => 'https://domains.xpsystems.eu',
            'route'      => '/domains',
            'link_label' => 'View domain list',
        ],
        [
            'value'      => 'Live',
            'label'      => 'Infrastructure Monitored',
            'url'        => 'https://status.xpsystems.eu',
            'link_label' => 'View system status',
        ],
        [
            'value'      => 'Open',
            'label'      => 'Source Projects',
            'url'        => 'https://oss.ternis.org',
            'route'      => '/opensource',
            'link_label' => 'Browse Open Source',
        ],
    ],

    'domain_groups' => [
        [
            'title'     => 'Parent Entity & Identity (ternis.dev)',
            'accent'    => 'accent',
            'highlight' => true,
            'domains'   => [
                ['domain' => 'ternis-edv.de',    'badge' => 'Parent'],
                ['domain' => 'ternis.dev',       'badge' => 'Parent'],
                ['domain' => 'oss.ternis.org',   'badge' => 'Open Source'],
                ['domain' => 'ternis.net',       'badge' => 'Nameserver'],
                ['domain' => 'ternismail.de',    'badge' => 'Mail'],
                ['domain' => 'ternis.eu'],
                ['domain' => 'fabianternis.dev'],
                ['domain' => 'fabianternis.de'],
                ['domain' => 'fabian-ternis.de'],
                ['domain' => 'fternis.de'],
                ['domain' => 'ivoternis.de'],
                ['domain' => 'mysocials.me'],
                ['domain' => 'getsocials.link'],
                ['domain' => 'linkmy.name'],
                ['domain' => 'pleasehireme.eu'],
                ['domain' => 'pleasehireme.de'],
            ],
        ],
        [
            'title'     => 'XP-Systems Network',
            'accent'    => 'accent',
            'highlight' => true,
            'domains'   => [
                ['domain' => 'xpsystems.eu'],
                ['domain' => 'xpsystems.de'],
                ['domain' => 'xpsys.de'],
                ['domain' => 'dnbx.de', 'badge' => 'API'],
                ['domain' => 'xp-mail.eu'],
                ['domain' => 'xp-ad.de'],
                ['domain' => 'ptero01.eu'],
                ['domain' => 'epyc01.eu'],
                ['domain' => 'ryzen01.eu'],
            ],
        ],
        [
            'title'   => 'EuropeHost Network',
            'accent'  => 'accent',
            'domains' => [
                ['domain' => 'europehost.eu'],
                ['domain' => 'eudomains.eu'],
                ['domain' => '24mc.eu'],
                ['domain' => 'mchost24.eu'],
                ['domain' => 'nerax.eu'],
                ['domain' => 'swiftshare.eu'],
                ['domain' => 'eushare.eu'],
                ['domain' => 'domaingen.de'],
                ['domain' => 'dsc.pics',      'badge' => 'GitHub'],
                ['domain' => 'dcpic.eu',      'badge' => 'GitHub'],
                ['domain' => 'twch.pics'],
                ['domain' => 'mcserver.lol'],
            ],
        ],
        [
            'title'   => 'MTEX.dev & Projects',
            'accent'  => 'partner',
            'domains' => [
                ['domain' => 'mtex.dev',       'badge' => 'GitHub'],
                ['domain' => 'api-sandbox.de', 'badge' => 'GitHub'],
                ['domain' => 'sandbox-api.de'],
                ['domain' => 'gimy.site',      'badge' => 'GitHub'],
                ['domain' => 'getmy.blog'],
                ['domain' => 'getmy.name'],
                ['domain' => 'urlk.app'],
                ['domain' => 'yourlink.app'],
                ['domain' => 'csslib.eu'],
                ['domain' => 'anlink.eu'],
            ],
        ],
        [
            'title'   => 'Official & Protection',
            'accent'  => 'accent',
            'domains' => [
                ['domain' => 'bank-of-germany.de'],
                ['domain' => 'schulchat-rlp.de'],
                ['domain' => 'schulkampus-rlp.de'],
                ['domain' => 'bildungslogin-rlp.de'],
                ['domain' => 'bildungsbereich-rlp.de'],
                ['domain' => 'hhg-kl.eu'],
                ['domain' => 'staatliches-heinrich-heine-gymnasium-kaiserslautern.de'],
            ],
        ],
        [
            'title'   => 'Other Active Domains',
            'accent'  => 'accent',
            'domains' => [
                ['domain' => 'kaufenhof.de', 'badge' => 'Client'],
                ['domain' => 'heimatverein-floersheim-dalsheim.de'],
                ['domain' => 'woistdasdrachenei.de'],
                ['domain' => 'pythonhub.eu'],
                ['domain' => 'xmage.eu'],
                ['domain' => 'imagu.eu'],
                ['domain' => 'pyshop.de'],
                ['domain' => '2note.eu'],
                ['domain' => 'burgermc.de'],
                ['domain' => 'laravel-tutorial.eu'],
                ['domain' => 'gehirn-weg.de'],
                ['domain' => 'spielefrei.de'],
                ['domain' => 'xpgames.eu'],
                ['domain' => '192-168-0-1.de'],
                ['domain' => 'mail-free.eu', 'badge' => 'GitHub'],
                ['domain' => 'eu-data.org',   'badge' => 'GitHub'],
                ['domain' => 'eu-search.org', 'badge' => 'GitHub'],
                ['domain' => 'web-search.org','badge' => 'GitHub'],
            ],
        ],
        [
            'title'   => 'Legacy (Expired)',
            'accent'  => 'accent',
            'legacy'  => true,
            'domains' => [
                ['domain' => 'xp-craft.de'],
                ['domain' => 'darkangel-mc.de'],
                ['domain' => 'XP-Host.de'],
                ['domain' => 'ebay-konto.de'],
                ['domain' => 'CityCraft-NW.de'],
                ['domain' => 'mail-free.de'],
                ['domain' => 'michaelninder.de'],
                ['domain' => 'XP-Link.de'],
                ['domain' => 'DogWaterDev.de'],
                ['domain' => 'XP-Node.de'],
                ['domain' => 'Dexify.eu'],
                ['domain' => 'XP-Cloud.eu'],
                ['domain' => 'Code-Trainer.de'],
                ['domain' => 'A-Sub.de'],
                ['domain' => 'B-Sub.de'],
                ['domain' => 'HHGkl.de'],
                ['domain' => 'CityCraft-SMP.de'],
                ['domain' => 'QuizHive.de'],
                ['domain' => 'Bank-of-Europe.eu'],
                ['domain' => 'CraftAttack.xyz'],
                ['domain' => 'EuroMC.eu'],
                ['domain' => 'XP-H.de'],
                ['domain' => 'XP-L.de'],
                ['domain' => 'Sub2.eu'],
                ['domain' => 'WebStruct.eu'],
                ['domain' => 'McServerTools.eu'],
                ['domain' => 'XPHost.eu'],
                ['domain' => 'MCPractice.eu'],
                ['domain' => 'NovaStack.eu'],
                ['domain' => 'FlexiStack.eu'],
                ['domain' => 'PelicanHost.eu'],
                ['domain' => 'axiohost.eu'],
                ['domain' => 'axiohost.de'],
                ['domain' => 'city-craft.de'],
                ['domain' => 'XP-Domains.de'],
                ['domain' => 'XP-Domain.de'],
                ['domain' => 'xfolio.eu'],
                ['domain' => 'eupractice.eu'],
                ['domain' => 'soulnode.eu'],
            ],
        ],
    ],

    'github' => [
        'sources' => [
            [
                'handle'      => 'ternis',
                'type'        => 'org',
                'label'       => 'oss.ternis.org',
                'description' => 'Official open-source ecosystem, core repositories & infrastructure automation (oss.ternis.org).',
                'url'         => 'https://oss.ternis.org',
            ],
            [
                'handle'      => 'xpsystems',
                'type'        => 'org',
                'label'       => 'xpsystems',
                'description' => 'Core infrastructure, tools, and services.',
                'url'         => 'https://github.com/xpsystems',
            ],
            [
                'handle'      => 'xpsystems-ai',
                'type'        => 'user',
                'label'       => 'xpsystems-ai',
                'description' => 'AI-assisted tooling and automation projects.',
                'url'         => 'https://github.com/xpsystems-ai',
            ],
        ],
        'team_github_handles' => ['fabianternis', 'dogwaterdev'],
    ],

    'status' => require __DIR__ . '/status.php',
];

