<?php

declare(strict_types=1);

$storageDir = dirname(__DIR__) . '/data/status';

return [
    'site' => [
        'name'        => 'xpsystems Status',
        'domain'      => 'status.xpsystems.eu',
        'org'         => 'xpsystems',
        'org_url'     => 'https://xpsystems.eu',
        'github_url'  => 'https://github.com/xpsystems',
        'mtex_status' => 'https://status.mtex.dev',
        'api_base'    => '',
        'playground'  => 'https://api-sandbox.de/playground.html',
        'version'     => '4.2.0',
    ],
    'cache' => [
        'ttl'  => 90,
        'path' => $storageDir . '/status.json',
        'dir'  => $storageDir,
    ],
    'history' => [
        'path'        => $storageDir . '/history.json',
        'max_entries' => 1440,
    ],
    'db' => [
        'driver'      => extension_loaded('pdo_sqlite') ? 'sqlite' : 'none',
        'sqlite_path' => $storageDir . '/status.db',
        'mysql_host'     => '127.0.0.1',
        'mysql_port'     => 3306,
        'mysql_dbname'   => 'xpsystems_status',
        'mysql_user'     => 'db_user',
        'mysql_password' => 'db_password',
    ],
    'ping' => [
        'timeout'   => 6,
        'useragent' => 'xpsystems-statusbot/1.0 (+https://status.xpsystems.eu)',
    ],
    'check' => [
        'token' => '',
    ],
    'services' => [
        // ── Core ────────────────────────────────────────────────────────────
        [
            'slug'        => 'xpsystems-eu',
            'name'        => 'xpsystems.eu',
            'group'       => 'Core',
            'url'         => 'https://xpsystems.eu',
            'ping_url'    => 'https://xpsystems.eu',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'xpsystems-de',
            'name'        => 'xpsystems.de',
            'group'       => 'Core',
            'url'         => 'https://xpsystems.de',
            'ping_url'    => 'https://xpsystems.de',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'xpsys-de',
            'name'        => 'xpsys.de',
            'group'       => 'Core',
            'url'         => 'https://xpsys.de',
            'ping_url'    => 'https://xpsys.de',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'contact-xpsystems-eu',
            'name'        => 'contact.xpsystems.eu',
            'group'       => 'Core',
            'url'         => 'https://contact.xpsystems.eu',
            'ping_url'    => 'https://contact.xpsystems.eu',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'domains-xpsystems-eu',
            'name'        => 'domains.xpsystems.eu',
            'group'       => 'Core',
            'url'         => 'https://domains.xpsystems.eu',
            'ping_url'    => 'https://domains.xpsystems.eu',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'opensource-xpsystems-eu',
            'name'        => 'opensource.xpsystems.eu',
            'group'       => 'Core',
            'url'         => 'https://opensource.xpsystems.eu',
            'ping_url'    => 'https://opensource.xpsystems.eu',
            'is_deployed' => true,
        ],

        // ── Hosting ─────────────────────────────────────────────────────────
        [
            'slug'        => 'europehost-eu',
            'name'        => 'EuropeHost.eu',
            'group'       => 'Hosting',
            'url'         => 'https://europehost.eu',
            'ping_url'    => 'https://europehost.eu',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'eudomains-eu',
            'name'        => 'eudomains.eu',
            'group'       => 'Hosting',
            'url'         => 'https://eudomains.eu',
            'ping_url'    => 'https://eudomains.eu',
            'is_deployed' => false,
        ],
        [
            'slug'        => 'eushare-eu',
            'name'        => 'eushare.eu',
            'group'       => 'Hosting',
            'url'         => 'https://eushare.eu',
            'ping_url'    => 'https://eushare.eu',
            'is_deployed' => false,
        ],
        [
            'slug'        => 'swiftshare-eu',
            'name'        => 'swiftshare.eu',
            'group'       => 'Hosting',
            'url'         => 'https://swiftshare.eu',
            'ping_url'    => 'https://swiftshare.eu',
            'is_deployed' => false,
        ],
        [
            'slug'        => 'dsc-pics',
            'name'        => 'dsc.pics',
            'group'       => 'Hosting',
            'url'         => 'https://dsc.pics',
            'ping_url'    => 'https://dsc.pics',
            'is_deployed' => false,
        ],

        // ── Sovereignty ─────────────────────────────────────────────────────
        [
            'slug'        => 'eu-data-org',
            'name'        => 'eu-data.org',
            'group'       => 'Sovereignty',
            'url'         => 'https://eu-data.org',
            'ping_url'    => 'https://eu-data.org',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'mail-free-eu',
            'name'        => 'mail-free.eu',
            'group'       => 'Sovereignty',
            'url'         => 'https://mail-free.eu',
            'ping_url'    => 'https://mail-free.eu',
            'is_deployed' => false,
        ],
        [
            'slug'        => 'eu-search-org',
            'name'        => 'eu-search.org',
            'group'       => 'Sovereignty',
            'url'         => 'https://eu-search.org',
            'ping_url'    => 'https://eu-search.org',
            'is_deployed' => true,
        ],

        // ── Developer ────────────────────────────────────────────────────────
        [
            'slug'        => 'api-sandbox-de',
            'name'        => 'api-sandbox.de',
            'group'       => 'Developer',
            'url'         => 'https://api-sandbox.de',
            'ping_url'    => 'https://api-sandbox.de',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'status-node-1',
            'name'        => 'status.xpsystems.eu',
            'group'       => 'Developer',
            'url'         => 'https://status.xpsystems.eu',
            'ping_url'    => 'https://status.xpsystems.eu/api/ping',
            'is_deployed' => true,
        ],
        [
            'slug'        => 'status-node-2',
            'name'        => 'status.xpsys.de',
            'group'       => 'Developer',
            'url'         => 'https://status.xpsys.de',
            'ping_url'    => 'https://status.xpsys.de/api/ping',
            'is_deployed' => true,
        ],
    ],
    'groups' => ['Core', 'Hosting', 'Sovereignty', 'Developer'],
    'api_endpoints' => [
        [
            'method'      => 'GET',
            'path'        => '/api/status',
            'summary'     => 'Overall system status summary',
            'description' => 'Returns the aggregated operational status across all monitored services, plus a count breakdown by status.',
            'params'      => [],
            'request'     => "GET /api/status HTTP/1.1\nHost: status.xpsystems.eu\nAccept: application/json",
            'response'    => '{"overall":"operational","checked_at":1770000000,"summary":{"total":12,"up":12,"degraded":0,"down":0,"unknown":0,"not_deployed":5}}',
        ],
        [
            'method'      => 'GET',
            'path'        => '/api/services',
            'summary'     => 'All monitored services and their current status',
            'description' => 'Returns the full list of services with their current status, HTTP response code, and latency in milliseconds.',
            'params'      => [],
            'request'     => "GET /api/services HTTP/1.1\nHost: status.xpsystems.eu\nAccept: application/json",
            'response'    => '{"checked_at":1770000000,"services":[{"slug":"xpsystems-eu","name":"xpsystems.eu","group":"Core","url":"https://xpsystems.eu","is_deployed":true,"status":"up","http_code":200,"latency_ms":142}]}',
        ],
        [
            'method'      => 'GET',
            'path'        => '/api/service/{slug}',
            'summary'     => 'Individual service status by slug',
            'description' => 'Returns the current status for a single service identified by its slug.',
            'params'      => [
                ['name' => 'slug', 'in' => 'path', 'required' => true, 'description' => 'Service slug — e.g. xpsystems-eu'],
            ],
            'request'     => "GET /api/service/xpsystems-eu HTTP/1.1\nHost: status.xpsystems.eu\nAccept: application/json",
            'response'    => '{"checked_at":1770000000,"service":{"slug":"xpsystems-eu","name":"xpsystems.eu","group":"Core","url":"https://xpsystems.eu","is_deployed":true,"status":"up","http_code":200,"latency_ms":142}}',
        ],
        [
            'method'      => 'GET',
            'path'        => '/api/history',
            'summary'     => 'Full check history — all services, last N checks',
            'description' => 'Returns the most recent check entries across all services. Each entry contains a Unix timestamp, overall status, and per-service results.',
            'params'      => [
                ['name' => 'limit', 'in' => 'query', 'required' => false, 'description' => 'Number of entries to return (default: 90, max: 1440)'],
            ],
            'request'     => "GET /api/history?limit=2 HTTP/1.1\nHost: status.xpsystems.eu\nAccept: application/json",
            'response'    => '{"count":2,"entries":[{"ts":1770000000,"overall":"operational","services":{"xpsystems-eu":{"status":"up","latency_ms":142,"http_code":200}}}]}',
        ],
        [
            'method'      => 'GET',
            'path'        => '/api/history/{slug}',
            'summary'     => 'Per-service check history with uptime stats',
            'description' => 'Returns per-day aggregated uptime stats and an overall summary for a single service over the last N days.',
            'params'      => [
                ['name' => 'slug', 'in' => 'path',  'required' => true,  'description' => 'Service slug'],
                ['name' => 'days', 'in' => 'query', 'required' => false, 'description' => 'Days to look back (default: 90, max: 3650)'],
            ],
            'request'     => "GET /api/history/xpsystems-eu?days=90 HTTP/1.1\nHost: status.xpsystems.eu\nAccept: application/json",
            'response'    => '{"slug":"xpsystems-eu","summary":{"uptime_pct":99.98,"avg_latency_ms":142,"days_monitored":90},"days":[{"date":"2026-09-05","uptime_pct":100,"avg_latency_ms":138,"had_outage":false}]}',
        ],
        [
            'method'      => 'GET',
            'path'        => '/api/day/{slug}/{YYYY-MM-DD}',
            'summary'     => 'All checks and incidents for a service on a specific day',
            'description' => 'Returns every recorded check, incident periods with start/end timestamps and real downtime calculation.',
            'params'      => [
                ['name' => 'slug', 'in' => 'path', 'required' => true, 'description' => 'Service slug'],
                ['name' => 'date', 'in' => 'path', 'required' => true, 'description' => 'Date in YYYY-MM-DD format (UTC)'],
            ],
            'request'     => "GET /api/day/xpsystems-eu/2026-09-05 HTTP/1.1\nHost: status.xpsystems.eu\nAccept: application/json",
            'response'    => '{"slug":"xpsystems-eu","date":"2026-09-05","summary":{"uptime_pct":100,"down_secs":0,"degraded_secs":0,"avg_latency_ms":142},"checks":[],"incidents":[]}',
        ],
        [
            'method'      => 'GET',
            'path'        => '/api/ping',
            'summary'     => 'Liveness probe',
            'description' => 'Lightweight probe returning pong with current server timestamp and host.',
            'params'      => [],
            'request'     => "GET /api/ping HTTP/1.1\nHost: status.xpsystems.eu\nAccept: application/json",
            'response'    => '{"pong":true,"timestamp":1770000000,"server":"status.xpsystems.eu"}',
        ],
    ],
];
